### ISSUE TITLE
The plugin doesn't respond to selection change

### ISSUE THREAD

**Issue by MrBiscuit** [aaroniker/figma-easometric#1]
Currently, you have to reopen the plugin UI every time you change a selection on the canvas, otherwise, this plugin will continue to edit the old selection. There is a dedicated Figma API on selection change (https://www.figma.com/plugin-docs/api/properties/figma-on/) see if this helps.

With that said, this is a great plugin, keep up the good work :)

**Comment by aaroniker** [comment]
@MrBiscuit thanks for reporting - i will take a look!

**Comment by aaroniker** [comment]
Done https://github.com/aaroniker/figma-easometric/commit/a89f00112107d38662ef0a0c0aee026442053364
Thanks again for reporting!
