### ISSUE TITLE
How to disable the isometric effect?

### ISSUE THREAD

**Issue by renuka-geo** [aaroniker/figma-easometric#2]
This plugin has been very handy and I love it but I do have one issue, how do I disable the isometric effect on an object? Like for example, I create an element and apply the easometric Top Right. Then realise I don't want that effect (like after a lot of changes so I can't undo)

Is there a way to remove/disable this effect? Thank you :)

**Comment by aaroniker** [comment]
@renuka-geo thanks for your feedback!
if you select that layer/group again, isn't there an active state at the modal?

**Comment by renuka-geo** [comment]
Oh yeah! I feel so stupid, I didn't realise that lol. Thank you, it worked.

**Comment by aaroniker** [comment]
@renuka-geo youre welcome!
